import { Component, EventEmitter, Output } from '@angular/core';
import { CommonModule } from '@angular/common';

// interface for the view type
type View = 'dashboard' | 'about' | 'metrics';

@Component({
  selector: 'app-metrics',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './metrics.component.html',
  styles: `
    :host {
      display: block;
      min-height: 100vh;
      width: 100vw;
    }
  `
})
export class MetricsComponent {
   @Output() viewChangeRequest = new EventEmitter<View>();

  ecologicalMetrics = [
    { metric: 'Carbon Sequestration', unit: 'Tonnes of CO2e', focus: 'Calculated annual CO2 absorbed by planted/protected area.' },
    { metric: 'Biodiversity Index', unit: 'Score (e.g., 0-100)', focus: 'Based on species counts (flora/fauna) or proxy measures.' },
    { metric: 'Water Retention Capacity', unit: 'Litres or % change', focus: 'Measure of soil quality improvement or watershed protection efficiency.' },
    { metric: 'Deforestation Rate', unit: 'Hectares / % change', focus: 'Tracks reduction in forest loss compared to a baseline.' },
    { metric: 'Area of Reforestation', unit: 'Hectares', focus: 'Total land successfully replanted (aligns with "Trees Planted" metric).' },
  ];

  socialMetrics = [
    { metric: 'Jobs Created', unit: 'Number of people', focus: 'Full-time equivalent (FTE) jobs provided (e.g., rangers, seedling production).' },
    { metric: 'IGA Success Rate', unit: '% of projects active', focus: 'Measures the sustainability of Income Generating Activities (IGAs) you are tracking.' },
    { metric: 'Access to Resources', unit: '% of community', focus: 'Increase in access to sustainable food, water, or medicinal plants.' },
    { metric: 'Training Hours Delivered', unit: 'Hours', focus: 'Total time spent training community members in sustainable forestry or IGAS.' },
    { metric: 'Local Revenue Generated', unit: 'Currency', focus: 'Total revenue generated by community-led forest products/services.' },
  ];

  economicalMetrics = [
    { metric: 'Cost Per Tree Planted', unit: 'Currency / Tree', focus: 'Efficiency metric for resource allocation and management.' },
    { metric: 'Project Financial Viability', unit: 'Score / Status', focus: 'Simple rating based on funding secured vs. expenditures.' },
    { metric: 'Ecotourism Revenue', unit: 'Currency', focus: 'Revenue generated from guided tours, recreational activities, or related services.' },
    { metric: 'Investment Leverage Ratio', unit: 'Ratio', focus: 'Measures how much private/grant funding is attracted per dollar spent.' },
    { metric: 'Yield of Non-Timber Products', unit: 'Kilograms / Volume', focus: 'Harvested amount of sustainable products (e.g., honey).' },
  ];
}

